#spring:
#  profiles: test
#  datasource:
#    datasource:
#      driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
#      url: jdbc:tc:mysql:5.7.22:///test_db
#      username: root
#      password: test1234!
spring:
  datasource:
    username: root
    password: sandwich1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/subway

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


  output:
    ansi:
      enabled: always
logging:
  level:
    com:
      info
